### ISSUE TITLE
JAWS + Firefox 60 Test

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#142]
For some reason JAWS + Firefox 60 isn't reading alerts 100% of the time. See phetsims/resistance-in-a-wire/issues/165.

@jessegreenberg, please provide the JSFiddle link. 

To test this, and to help get a better understanding of the problem, please test this [JSFiddle](http://jsfiddle.net/4znve8cr/34/).

1. Make sure all other applications are closed.
2. Use the latest version of Firefox.
3. Make sure JAWS is up-to-date.
4. Keep a record of how often JAWS reads alerts.

Something like this would be useful...

| Actions Performed | Alerts Read |
| -- | -- |
| 20 | 15 |

Maybe try waiting a few seconds before performing an action that requires an alert.

Assigning @ariel-phet for prioritization.

**Comment by jessegreenberg** [comment]
In terms of priority, we will have to figure this out before publishing resistance-in-a-wire. There is a chance this won't even show up at all in a JSFiddle. This will just help us determine whether this is a Browser/AT bug, or whether the original issue is related to performance in the PhET sim.

**Comment by jessegreenberg** [comment]
I updated the link in the original ticket with a link to a JSFiddle that tests this. We should here something like
"New value for the slider is #".
"Alert: Slider value changed to #."

Testing it with JAWS on FF 61.0.1, I get both statements 100% of the time. This indicates that this is caused by performance in RIAW. @lmulhall-phet @JRomero0613 feel free to test if you wish but I believe that this verifies that this is not a general JAWS problem.

**Comment by jessegreenberg** [comment]
Thanks for opening this issue @lmulhall-phet, feel free to close if you agree.

**Comment by JRomero0613** [comment]
@jessegreenberg I have just tested the fiddle and I am also getting both statements 100% of the time. I agree that this is an issue caused by the RIAW sim.

**Comment by lmulhall-phet** [comment]
Sounds good! Thanks, @JRomero0613. Closing.
