### ISSUE TITLE
Testing the ios app version 1.2

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#168]
QA, please do some general testing on the latest TestFlight version of the ios app (1.2 Build 10).  Please check to make sure that the new table view and the 3 tab navigation bar are working on iphones.  We should also check most of the app on ipads to verify that there have not been any regressions.

We are already aware of the following issues, so if you observe these please ignore them for now: https://github.com/phetsims/phet-ios-app/issues/316

**Comment by KatieWoe** [comment]
@mattpen Not sure if this is an issue or intentional, so putting here as a question.
The new version of the app on iOS 9.3.5 on iPad2 seems to have elongated or slightly off proportions on the blue refresh button and the red heart button.  They also seem to be brushing up against the bottom of their bar (hard to see on screenshot).

Image of old version:
![image](https://user-images.githubusercontent.com/41024075/44109139-80122c4e-9fb9-11e8-84a7-07d1ad9b5992.png)

Image of new version:
![image 1](https://user-images.githubusercontent.com/41024075/44109157-8e8f701a-9fb9-11e8-8929-6151dcdd8f7e.png)

**Comment by lmulhall-phet** [comment]
Notice the details tag arrow in the table view on an iPad:

![img_0169](https://user-images.githubusercontent.com/31285590/44119934-f49f6b6c-9fd7-11e8-9047-4fa9cafece11.PNG)

And when the details are expanded:

![img_0170](https://user-images.githubusercontent.com/31285590/44120007-311c9e84-9fd8-11e8-8ece-0195d43c52f3.PNG)

Shouldn't it be a downward facing arrow instead of a checkmark?

**Comment by KatieWoe** [comment]
@mattpen QA has found as much as I think we can in this version.

**Comment by ariel-phet** [comment]
Closing this issue, since we have a new build, and much of this testing has occurred on a n older version
