### ISSUE TITLE
Ipad2 test for Molecules and Light

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#25]
I recently reverted some workaround code for removing the 'Return Molecule' button from the observation window (see https://github.com/phetsims/molecules-and-light/commit/672fb1d1bc555ed4f2ca043fcee9b3d85cf2ab9a and https://github.com/phetsims/molecules-and-light/commit/2feff3f3b38e6da0965b8b6d666353b23f58bc72). For optimization purposes, we were setting the opacity in an effort to better optimize the performance.

Since https://github.com/phetsims/molecules-and-light/issues/98 and https://github.com/phetsims/scenery/issues/404 are both closed, I reverted back to explicitly setting the visibility on the button.

To test, break a molecule apart (UV + NO2 works well). The button will appear, and we can either click the button to return the molecule or select a new molecule which will remove the button and render the new molecule in the observation window.

**Comment by mbarlow12** [comment]
@ariel-phet That's correct, though I'd be happy to give that a go in the office tomorrow.

**Comment by ariel-phet** [comment]
@mbarlow12 when possible, always good to give a quick sanity check before handing to QA (unless urgent and no access to a device). Assigning back to you for the moment.

**Comment by ariel-phet** [comment]
@mbarlow12 were you able to do this test?

**Comment by mbarlow12** [comment]
Not yet—the question is about some notes on performance, and I currently don't know how to check that data.

**Comment by ariel-phet** [comment]
@mbarlow12 Feel free to ask @phet-steele for guidance/help

**Comment by mbarlow12** [comment]
Will do—I'll also start with JB and JO about how they found the issue in the first place. Thanks.

**Comment by jessegreenberg** [comment]
The original issue was https://github.com/phetsims/molecules-and-light/issues/91.  We expect it to no longer be a problem because https://github.com/phetsims/scenery/issues/404 (performance issues when adding and removing drawables with gradients) has been closed.  The workaround was removed in the workaround was removed in https://github.com/phetsims/molecules-and-light/commit/2feff3f3b38e6da0965b8b6d666353b23f58bc72.

I think the only thing we need to verify is that we don't see a significant drop in framerate when the "Return Molecule" button becomes visible on iPad2 and iPad3.

**Comment by mbarlow12** [comment]
@jessegreenberg and I tested this afternoon and found no issues. Closing.
