### ISSUE TITLE
Should en be tested instead of all?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#331]
In discussion of https://github.com/phetsims/QA/issues/330, it was noted that sims were tested with the _all_ link, but sims are published with the _en_ link.  We are looking into _en_ sims on phet-dev will work, but either way, many developers wondered if testing _en_ would work better.  At the moment, _all_ is tested for consistency, but I am unaware of any other reason it would be preferred.  @phet-steele do you know any deeper reasons for this/any reason using _en_ might be detrimental?

**Comment by phet-steele** [comment]
> @phet-steele do you know any deeper reasons for this/any reason using _en_ might be detrimental?

It was my understanding that _all.html is a better catch all? We use those versions in offline products (ie. the installer and the app [which would probably be used on an iPad Pro!!!]), and it shouldn't be different enough from sims built for specific locales, right?

If we are encountering an issue with the _all.html on _one_ platform, does that really mean we should stop testing it all together? I would think we would either a). figure out why the _all.html is broken on the one platform and fix it, or b). just use the _en.html on the one platform and none of the others. Otherwise, this sounds like one of those sledgehammer and nail situations. What are advantages to testing only the .en_html?

Regarding point a)., I think this is _**exactly why**_ we test the _all.html file: to find bugs with it. It's weird to me that we are advocating to change the testing protocol so quickly. This is similar to if we found a bug in a sim and just said, "Eh, let's just not test that version of the sim and ignore the bug".

Disclaimer: testing both of these versions wouldn't be "detrimental" to anything other than time.

**Comment by KatieWoe** [comment]
To be clear, I don't think we should stop testing _all_ or that the solution to it potentially not working is to stop supporting it.  A few developers thought it would be more useful to test _en_ and I didn't have enough information to say why we use _all_.  Thanks for the input.

**Comment by ariel-phet** [comment]
Sounds good, I think we can certainly continue testing with the _all.html, just wanted to know all the previous history and reasoning. @KatieWoe feel free to close
