### ISSUE TITLE
Why was QA repo added to active-repos?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#655]
In https://github.com/phetsims/perennial/commit/31b2969a9e3a81368121f6bd7b8813b472069d55#diff-0bc256e89a89ebc0b724a4e7ab023c2c43430a0f5c6c3865b4db2e65f91554a0, @samreid added QA to active-repos. There's nothing in the commit message to indicate why it was added.  I don't recall a Slack announcement that it was added (I might have missed it).  No one on Slack knew why it was added - it contains no code or scripts. And it was confusing that it suddenly showed up in clone-missing-repo.sh when @chrisklus announced the addition of counting-common. 

@samreid why QA repo added to active-repos?

**Comment by pixelzoom** [comment]
In Slack, @KatieWoe said:
> I think @samreid was looking for the issue templates and added it so it would be easier to find? You would need to ask him to be sure though.

**Comment by samreid** [comment]
What brought it to my attention recently was my need for an issue template.  I typically have the QA issue checked out, not sure why my local copy got erased, but I was surprised to see it wasn't an active-repo, since it contains information that we actively use and maintain.

> And reading/editing .md files is a better experience on the GitHub site.

My personal preference is to read and edit these in my IDE, am I the only one?

Looking through the commit history, I see commits from:
@jessegreenberg 
@terracoda 
@KatieWoe 
@pixelzoom
@liam-mulhall 
@zepumph 
@samreid 
@Denz1994 
@jbphet 

It would be useful to find search results in the qa-books, if we are making changes that affect them.

Is there a good reason to remove QA from the active repos?

**Comment by pixelzoom** [comment]
> Is there a good reason to remove QA from the active repos?

No. I'm fine with it being in active-repos.  This issue probably wouldn't have been created if it was announced that it had been added, instead of mysteriously appearing the next time a new repo was added.

**Comment by chrisklus** [comment]
One small thing for me is that it's the only repo in my `phetsims` directory that is capitalized. not a big deal, but it was enough of a reason for me to instinctively delete it when i first got it from clone-missing-repos, so thought it was work noting

**Comment by KatieWoe** [comment]
It also doesn't seem to work on master (it keeps saying pull failed)

**Comment by jessegreenberg** [comment]
The capitalization is related to the pull failure on phettest, see https://github.com/phetsims/phetmarks/issues/51

**Comment by samreid** [comment]
I messaged slack:

> The QA repo was added to active-repos, please pull perennial and run clone-missing-repos.sh at your convenience.  Details are in https://github.com/phetsims/QA/issues/655

Regarding:

> One small thing for me is that it's the only repo in my `phetsims` directory that is capitalized. 

I would also recommend a lowercase repo name.

**Comment by samreid** [comment]
Thanks, let's close this issue and continue about the casing in https://github.com/phetsims/phetmarks/issues/51
