### ISSUE TITLE
Investigate GEE performance

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#76]
All hands on deck for this one, please. We need to figure out everything we can about https://github.com/phetsims/gene-expression-essentials/issues/111 as soon as possible.

See https://github.com/phetsims/gene-expression-essentials/issues/111#issuecomment-350051657 for a table of occurrences (could be inaccurate, that's the point of this investigation).

See https://github.com/phetsims/gene-expression-essentials/issues/111#issuecomment-350111061 for the weird case we are investigating.

And finally see https://github.com/phetsims/gene-expression-essentials/issues/111#issuecomment-350398315 for the goals of this investigation.

**Comment by arnabp** [comment]
Nothing concrete, but I'll put some findings that'll hopefully help other people not waste time. All of this is in Mac 10.11: I've found no increase in the probability of this happening over time (no apparent memory leaks, I've left the sim running for 20 minutes without the issue appearing). When the problem comes up, sometimes restarting safari makes the issue go away and sometimes it doesn't. CPU, Memory, Disk, and Network readings in activity monitor all seem normal when the problem occurs, and the in-sim profiler doesn't register a drop in frames. I'm still trying to find a way to consistently make the bug appear, but so far it still appears to be random.

**Comment by arnabp** [comment]
The best way I've come up with to reproduce this so far is just to try again and again one tab after another. The rate at which the bug comes up seems to be about 40% (I've tested 33 tabs and come up positive on 13 of them). 

Note that this doesn't work by simply refreshing a single tab. In fact, if a tab does (or does not) have the bug, refreshing it will not change that status. Bugged tabs will keep the bug no matter how many times they're refreshed (and vice versa).

**Comment by phet-steele** [comment]
The above procedure has never revealed an issue in later Safari versions (@arnabp was using Safari 9). I think we should just recommend to users to update. Thanks team.
